services:
# __AGENT_SERVICES__

  monitor:
    build: ./.swarm/monitor
    ports:
      - "${MONITOR_PORT:-__MONITOR_PORT__}:3000"
    volumes:
      - ./.swarm/tickets:/tickets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
